---
- name: Update Ubuntu system using sudo apt-get update
  hosts: all
  become: yes
  tasks:
    - name: Run sudo apt-get update
      command: apt-get update
      register: update_result
      ignore_errors: yes

    - name: Show update success message
      debug:
        msg: "apt-get update completed successfully!"
      when: update_result.rc == 0

    - name: Show update failure message
      debug:
        msg: "apt-get update failed!"
      when: update_result.rc != 0
