---
- name: Update Ubuntu system using apt-get
  hosts: all
  become: yes
  tasks:
    - name: Run apt-get update
      command: apt-get update

    - name: Run apt-get upgrade
      command: apt-get upgrade -y

    - name: Run apt-get dist-upgrade
      command: apt-get dist-upgrade -y

    - name: Run apt-get autoremove
      command: apt-get autoremove -y

    - name: Run apt-get autoclean
      command: apt-get autoclean -y
